version: "3.4"

services:
  helios-example:
    image: helios-example
    restart: on-failure
    build:
      context: ./
    ports:
      - 6006:6006
      - 24678:24678
      - 5173:5173
    tty: true
    stdin_open: true
    command: npm run storybook
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules